### PR TITLE
Fastqc@0.2.0

### PR DESCRIPTION
**Pull request by lindaxiang**

### CODE REVIEW

**Comment by RaqManzano** [comment]
Connected to #31

**Comment by lindaxiang** [comment]
> Do you need to add the file name to the json for the new FastQC info? In the same way it is done in L88.

Hi @RaqManzano , L88 has added the file name, so no need to add twice, right?

**Comment by RaqManzano** [comment]
That's absolutely right! Ok, good to go in my opinion then. Do you need to do some testing before we merge?

**Comment by lindaxiang** [comment]
> That's absolutely right! Ok, good to go in my opinion then. Do you need to do some testing before we merge?
The test cases are all passed, yeah. :-)

**Review by RaqManzano — APPROVED** [review]

**Pull request merged**
